features:
  node_user_picture: 0
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
slider_display: 1
slide1_title: 'Toy Review: "Age of the Primes" Carnivac vs Fisitron'
slide1_desc: 'Carnivac is a proud warrior facing off against the Autobot weapons master Fisitron!'
slide1_url: 'https://bwtf.com/toyreviews/generations/aotp/carnivac-vs-fisitron'
slide1_image:
  - '45'
slide2_title: 'Toy Review: "Generations Age of the Primes" Spinister vs Topspin'
slide2_desc: 'It''s Wrecker vs Mayhem Attack Squad member as Spinister and Topspin face off in the latest "Age of the Primes" two'
slide2_url: 'https://bwtf.com/toyreviews/generations/aotp/spinister-vs-topspin'
slide2_image:
  - '46'
slide3_title: 'Toy Review: "Cyberworld" Scorponok Strike Battle Set'
slide3_desc: "Lurking underneath the desert of Cyberworld is the gigantic and powerful Scorponok! Armed to the teeth with weaponry and raw power this Decepticon is the ultimate challenge for Autobots and Decepticons alike.\r\n"
slide3_url: 'https://www.bwtf.com/toyreviews/generations/legacy/breakdown-g2'
slide3_image:
  - '47'
slide4_title: 'Toy Review: "Age of the Primes" Big Convoy'
slide4_desc: 'Big Convoy is a powerful and fearsome warrior known among Maximals as "The One-Man Army". Still, when called upon he is a fantastic leader who cares about his warriors.'
slide4_url: 'https://bwtf.com/toyreviews/generations/aotp/bigconvoy'
slide4_image:
  - '48'
slide5_title: ''
slide5_desc: ''
slide5_url: ''
slide5_image: {  }
slide6_title: ''
slide6_desc: ''
slide56_url: ''
slide6_image: {  }
slide1_link_text: 'Read More'
slide2_link_text: 'Read More'
slide3_link_text: 'Read More'
slide4_link_text: 'Read More'
slide5_link_text: ''
slide6_link_text: ''
slide6_url: ''
slider_aspect: '16:9'
slider_overlay_preset: overlay-multiply
slider_overlay_from: 'rgba(0,0,0,.35)'
slider_overlay_to: 'rgba(0,0,0,.55)'
slider_autoplay_delay: '50000'
social1_platform: facebook
social1_url: 'https://www.facebook.com/bensworldtf/'
social2_platform: x-twitter
social2_url: 'https://x.com/BWTF_Ben/'
social3_platform: youtube
social3_url: 'https://www.youtube.com/channel/UCYb-KvhRv_CxCKBcwmz2p0A'
social4_platform: instagram
social4_url: 'https://instagram.com/BWTF_Ben/'
social5_platform: patreon
social5_url: 'https://www.patreon.com/bwtf_ben'
social6_platform: ''
social6_url: ''
social7_platform: ''
social7_url: ''
social8_platform: ''
social8_url: ''
